### ISSUE TITLE
A credit class with multiple projects breaks batch creation

### ISSUE THREAD

**Issue by aleem1314** [regen-network/regen-ledger#1032]
## Summary of Bug

If a credit class contains multiple projects, issuing a new credit batch fails with an error.

```
 simulate.go:300: error on block  23/100, operation (278/385) from x/ecocredit:
        failed to execute message; message index: 0: unique key violation [regen-network/cosmos-sdk@v0.45.0-regen-1/baseapp/baseapp.go:741]
```

This is because we are creating batch denom based on credit class.

## Version

master

## Steps to Reproduce

 - Create a credit class.
 - Create two projects.
 - Create one credit batch in each project. Second batch creation fails with an error `unique key violation`.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
Good catch. I'm thinking we either need to track batch sequence based on credit class or we need to update the batch denom to use or include project id... I think we might need to discuss this on our next product call.

**Comment by clevinson** [comment]
So @S4mmyb @ryanchristo and I had a few conversations today about longer term planning for projects and how our strategy for resolving this bug may actually need shifting in light of our long term aims.

Here's a summary of where we've gotten to:

Long term goals for projects are:
- projects should be able to be created in a permissionless manner by organizations / individuals wishing to register their project on-chain with some set of off-chain metadata (e.g. a metadata_url pointing to an IRI & resolver)
- project can "apply" to credit classes, which indicates a project's desire to engage in a process of adhering to a credit classes' methodology and having credits issued at certain points in time of a project's lifecycle (e.g. at hte conclusion of a monitoring period)
- the creator of the on-chain project is the default "project admin". Project admins can can perform update actions on the project like update metadata, apply to credit classes, and set a new project admin

With these goals in mind, @ryanchristo @S4mmyb and I had a hard time imagining how we could successfully upgrade our data model from its current formation (where auto-generated or custom project_id's are namespaced to a credit class) to the future iteration of projects which are divorced from credit classes entirely. We also revisited the need for custom project_id's, and @S4mmyb communicated that from his perspective that he doesn't see this as a strong requirement if there are good technical reasons against it.

While it may seem unwieldy to be changing requirements so close to being feature complete on v4.0, I think its important that we get the design of project IDs right, as we're launching `v1` of the proto files, and I'd like to minimize migrations when we later enable project creation to permissionless.

## Proposal 1

- Change project_id to:
  - be only auto incrementing, sequence it globally (not scoped to a credit class)
  - remove support for custom project_id's

This then means that project_id's are fully forward compatible with the long term goal for projects where they are not scoped to credit classes, and creation of them is permissionless.

### Option 1.a

Add an optional field to `project_id` called `origin_id` (similar to `origin_tx` in `MintBatchCredits`), which does not have enforced uniqueness (to prevent name squatting), but is used in an ORM secondary index.

Issuers of bridged credits could then create a project with `origin_id` = "V-35", and later that issuer/bridge operator could query for existing projects with `origin_id` == "V-35" if they want to issue more bridged credits to the same project.

### Option 1.b

Don't add any additional optional field.

When a bridge operator is issuing credits, they would need to check first if that Verra project exists on-chain by querying all projects, looking up off-chain metadata via an IRI & resolver for each project, and scanning the JSON-LD of each project's metadata for the corresponding Verra project ID (e.g. "V-35") in order to know whether they should create a new on-chain project or not.

## Proposal 2

We could alternatively not change anything for v4.0, and later when we migrate projects to be globally namespaced we then migrate all prior project_id's manually to either be converted into auto incrementing identifiers, or simply namespace all prior project_id's with the credit class under which they were initially instantiated.


## Summary

My preference is for 1.a. Despite the fact that its the most significant work now, it seems most aligned with our long term design for projects, as well as our current model for storing off-chain origin information in bridging transactions.  

Thoughts @aaronc @ryanchristo @S4mmyb ?

**Comment by ryanchristo** [comment]
> We could alternatively not change anything for v4.0.

We have to make changes to the current implementation of project ids because we have another separate but related issue, i.e. if a project is created with an auto-generated id under one credit class, a project cannot be created with an auto-generated id under another credit class, both projects would have a project id of `001` and the project id must be unique. We also have to update the batch denom as outlined in #1046 but maybe that was assumed alongside the proposals above.

**Comment by ryanchristo** [comment]
> We could alternatively not change anything for v4.0.

We have to update the format of the batch denom in order to solve the issue reported here. I'm guessing by not change anything you mean not changing the project id but we have to change the project id if we update the batch denom.

If we update the batch denom to include the project id, we need to exclude the class id from the auto-generated project id or else the batch denom would include the credit class id twice. If we make these changes as currently drafted in #1046, we introduce a new issue, i.e. if a project is created with an auto-generated id under one credit class, a project cannot be created with an auto-generated id under another credit class, the auto-generated id for both projects would be `001`.

As currently implemented in master, the auto-generated project id for the first project created under the `C01` credit class will be `C0101`. We could update this to `C01-001` and use the project id in the credit batch denom rather than using both the credit class id and the project id as currently drafted in #1046. This would solve both issues but we would still have project ids that include the class id and it sounds like we want to move away from a project being associated with a single credit class. We would also need to prefix custom project ids with the credit class id, i.e. when provided `V1`, the project id would become `C01-V1`.

The issue with global project ids is that we break the sequence pattern and the ability to read a batch denom from left to right, i.e. `001` in `C01-001-20200101-20210101-001` would no longer mean the first project of the `C01` credit class. I think we broke this pattern already when introducing custom project ids but we might want to remove custom project ids anyways, so we should also take into consideration an option that would allow us to maintain the pattern, i.e. `001` it the first batch of the first project of the first credit class of the `C` type.

It might be worth considering another proposal that focuses on solving our immediate needs but does not solve the issue with each on-chain project being coupled with a single credit class:

## Proposal 3

- remove support for custom project ids
- keep project sequence scoped to a credit class
- keep project creation permissioned based on credit class issuer
- prefix padded project sequence with credit class id to generate project ids that are always unique (e.g. `C01-001`) and use the project id in the batch denom instead of both the class id and project id (the project id includes the credit class id and the credit class includes the credit type and we do not break the sequence pattern)

Adding a field such as a `reference_id` without unique constraints is worth considering and it might serve a two purposes, (1) link on-chain projects that are the same on-the-ground project, and (2) convenient lookup.

I'm leaning towards focusing on our immediate concerns and sticking to our original intentions with the batch denom. I think we should expect some future migrations will be inevitable and if we want a way to preserve the batch denom, we should consider projects with multiple ids, one for each credit class, and a separate primary id that is not associated with a credit class.

**Comment by ryanchristo** [comment]
> We could alternatively not change anything for v4.0.

We have to update the format of the batch denom in order to solve the issue reported here. I'm guessing by not change anything you mean not changing the project id but we have to change the project id if we update the batch denom.

If we update the batch denom to include the project id, we need to exclude the class id from the auto-generated project id or else the batch denom would include the credit class id twice. If we make these changes as currently drafted in #1046, we introduce a new issue, i.e. if a project is created with an auto-generated id under one credit class, a project cannot be created with an auto-generated id under another credit class, the auto-generated id for both projects would be `001`.

As currently implemented in master, the auto-generated project id for the first project created under the `C01` credit class will be `C0101`. We could update this to `C01-001` and use the project id in the credit batch denom rather than using both the credit class id and the project id as currently drafted in #1046. This would solve both issues but we would still have project ids that include the class id. We would also need to prefix custom project ids with the credit class id, i.e. when provided `V1`, the project id would become `C01-V1` but maybe we should remove the ability to create custom project ids.

The issue with global project ids is that we break the sequence pattern and the ability to read a batch denom from left to right, i.e. `002` in `C01-002-20200101-20210101-003` would no longer mean the second project of the `C01` credit class. I think we broke this pattern already when introducing custom project ids but again, maybe we should remove the ability to create custom project ids. I think we should consider a proposal that preserves the sequence pattern, i.e. `C01-002-20200101-20210101-003` is the third batch of the second project of the first credit class of the `C` type.

I'm leaning towards focusing on our immediate concerns and sticking to our original intentions with the batch denom. I think we should expect some future migrations will be inevitable and if we want a way to preserve the batch denom, we should consider project entities that have a field that holds multiple ids, one for each credit class that they are a member of, and which is used when formatting the batch denom associated with each credit class, and then each project would have a separate primary id that is not associated with a credit class. This is not something we need to solve in the short-term though.

## Proposal 3

- remove support for custom project ids
- keep project sequence scoped to a credit class
- prefix padded project sequence with credit class id to generate project ids that are always unique (e.g. `C01-001`) and use the project id in the batch denom instead of both the class id and project id (the project id includes the credit class id)

Adding a field such as a `reference_id` without unique constraints is worth considering and it might serve a two purposes, (1) link on-chain projects that are the same on-the-ground project, and (2) convenient lookup.

**Comment by aaronc** [comment]
I really think this should be solved with two database tables:
* one for when a project is within a class, we could call this `ClassProject`
* one for a project which may relate to multiple classes, we could call this simply `Project`

`ClassProject` is basically what `Project` currently is. And my thinking is that its `class-project-id` should be `<class-id>-<proj-seq-or-custom-name>` (ex. `C01-001` or `C01-FOO`) and then batches would be `<class-project-id>-<start-date>-<end-date>-<seq>`. I think that's pretty much what we have now and I'm not sure I understand the issues with this.

`ClassProject` would contain a reference to `Project` which would contain generic metadata and jurisdiction information and an ID which is distinct from the current "class-level" project IDs we have now and which I'm mentioning above.

Would this address this?

**Comment by technicallyty** [comment]
> I really think this should be solved with two database tables:
> 
> * one for when a project is within a class, we could call this `ClassProject`
> * one for a project which may relate to multiple classes, we could call this simply `Project`
> 
> `ClassProject` is basically what `Project` currently is. And my thinking is that its `class-project-id` should be `<class-id>-<proj-seq-or-custom-name>` (ex. `C01-001` or `C01-FOO`) and then batches would be `<class-project-id>-<start-date>-<end-date>-<seq>`. I think that's pretty much what we have now and I'm not sure I understand the issues with this.
> 
> `ClassProject` would contain a reference to `Project` which would contain generic metadata and jurisdiction information and an ID which is distinct from the current "class-level" project IDs we have now and which I'm mentioning above.
> 
> Would this address this?

im leaning towards this solution. If custom project ID's are deemed required, i think it would make sense to limit them to 2-4 (instead of 2-16 as they are now) characters as to not bloat the batch denom.

Not too convinced with the `ClassProject` name, so I searched around google to see if there was a better word for "a group of projects" and `Program` came up, which seemed like a pretty good descriptor for the purpose you've described above. Curious to hear thoughts on that name

notes/tl;dr:
- introduce a `Program` table that contains the metadata/jurisdiction information
- `Project` stays mostly the same, but is now a child of a specific `Program`
- `BatchDenom` is now `<class-id>`-`<project-id>`-`<start-date>`-`<end-date>`-`<seq>`

**Comment by ryanchristo** [comment]
> Would this address this?

I think so. This aligns with my thinking. `ClassProject` sounds like a more flushed out version of what I was proposing for #883, where multiple project ids would exist that are class specific. I didn't think as far as how we would store information that is specific to the class-project relationship but that would be resolved with `ClassProject`.

> And my thinking is that its class-project-id should be <class-id>-<proj-seq-or-custom-name> (ex. C01-001 or C01-FOO) and then batches would be <class-project-id>-<start-date>-<end-date>-<seq>. I think that's pretty much what we have now and I'm not sure I understand the issues with this.

This solves the issue originally reported here and is aligned with what I have in #1046 with the exception of `class-project-id` being just `project-id` given `ClassProject` does not exist yet and projects are currently limited to a single credit class. I'm still not sure about custom project ids but I'm leaning towards removing support for custom project ids. It seems custom project ids  only add complexity such as how to prevent name squatting, whether or not to allow a custom id such as `001` or to require an alphabetical character, and keeping project sequence aligned with the number of projects per credit class.

> Not too convinced with the ClassProject name, so I searched around google to see if there was a better word for "a group of projects" and Program came up, which seemed like a pretty good descriptor for the purpose you've described above. Curious to hear thoughts on that name

I'm open to further discuss names but I think `ClassProject` makes sense given how we are currently naming join tables. The `Project` would be the project and the `ClassProject` would be the relationship between the project and a credit class.

> BatchDenom is now \<class-id>-\<project-id>-\<start-date>-\<end-date>-\<seq>

If we include the credit class id in the project id (or class project id) we would need to remove `<class-id>` from this pattern.
