### ISSUE TITLE
Implement CLI tests for commands without them

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-ledger#1047]
## Summary

Following the proposal of #1041, a discussion around whether we should migrate our client tests to unit tests now or wait for updates upstream that will make writing CLI commands and tests obsolete.

It was proposed that for now we treat CLI tests as a "nice to have" in the backlog while we explore our options. This issue tracks CLI commands that do not have tests.

- `buy-direct` https://github.com/regen-network/regen-ledger/pull/1078
- `buy-direct-batch` https://github.com/regen-network/regen-ledger/pull/1103
- ~~credit-type-proposal~~ cannot be tested
- `update-project-admin` https://github.com/regen-network/regen-ledger/pull/1102
- `update-project-metadata` https://github.com/regen-network/regen-ledger/pull/1105
- `allowed-denoms` https://github.com/regen-network/regen-ledger/pull/1106

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by technicallyty** [comment]
looking like proposals cannot be tested, or at least not included in our tests. I tested that a proposal was created, however, leaving this test in breaks the app because:

the gov module wraps proposal commands in tx flags. because of this, adding any txFlags (such a --from, and --yes) causes the app to panic during build. and since i cannot add these flags, the test *always* fails, as the `--yes` flag missing causes the transaction to not execute. 

luckily, through this process i was able to catch some errors and fix both proposal handlers, however, it looks like these will have to be tested manually on a testnet, or localnet.
