### ISSUE TITLE
Update state migrations to support latest changes

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#1049]
## Summary

We've made changes to state following the initial implementation of state migrations (#957). This issue tracks updates we need to make to state migrations following these changes.

- [x] Migrate credit types from params to new credit types ORM table #1061
- [ ] Migrate batch denom to new batch denom format

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
I've updated this issue to focus on state migration changes that need to be made since the initial implementation of state migrations and updated #980 to include new parameters that we need to add in the upgrade handlers; we don't need a state migration for adding a new parameter and adding new parameters would take place in the upgrade handlers.
