### ISSUE TITLE
ecocredit: mainnet migration audit updates

### ISSUE THREAD

**Issue by aleem1314** [regen-network/regen-ledger#1183]
## Summary of Bug

 - Basket creation fee is empty after migration. 
   - `basket_creation_fee` param changed to `basket_fee`.
- Batch Tradable supply is empty string
  - `tradable_supply` is showing `""` instead of `"0"`
     testnet: http://194.37.81.19:1317/regen/ecocredit/v1/batches/C01-002-20190101-20191231-002/supply
     mainnet: https://regen.api.ping.pub/regen/ecocredit/v1alpha1/batches/C01-20190101-20191231-002/supply

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
First item related to #1166

**Comment by ryanchristo** [comment]
I also noticed batch balance for escrowed credits was `""` rather than `"0"` after the migrations and we should address alongside the tradable supply issue.

**Comment by ryanchristo** [comment]
With regards to the basket fee, it looks like it was just the key that was not updated. I tested without changes and the migration seemed fine (state was updated and therefore querying for the param returned the expected result) but it was not possible to submit a param change proposal with `BasketFee` after the upgrade (but `BasketCreationFee` still worked). In order to update the basket fee, I think we need to reset the param in the upgrade handler but maybe there is a better way. See #1184

**Comment by ryanchristo** [comment]
I assigned myself to address the basket fee but have not started on the supply fix if @aleem1314 you want to take a look. We should also address the escrowed credit balance mentioned above https://github.com/regen-network/regen-ledger/issues/1183#issuecomment-1154327807
