### ISSUE TITLE
Upgrade codebase to ADR 028 addresses

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#211]
This may require some SDK changes and a new SDK release.

This is what enables Group accounts to be created in a way that is satisfies general SDK security requirements

Tasks:
- [ ] Update module keys to follow ADR-28 https://github.com/cosmos/cosmos-sdk/issues/7618

**Comment by robert-zaremba** [comment]
Duplicates https://github.com/cosmos/cosmos-sdk/issues/7618 ?

**Comment by clevinson** [comment]
If this is infact a duplicate, then we can just use this as a tracking issue on the regen ledger side.

**Comment by robert-zaremba** [comment]
Why not closing it? Why we need to track it on both side?

**Comment by aaronc** [comment]
We still need to upgrade the group module with these addresses.

**Comment by robert-zaremba** [comment]
Then let's rename this task to: _Upgrade codebase for ADR-028 addresses_

**Comment by clevinson** [comment]
This is blcoked until we upgrade to SDK v0.43

**Comment by robert-zaremba** [comment]
### Update

Originally I updated the `ModuleID` structure to use address instead of path. This attribute is used in a router for signature check. I think this is a hack. Module name is used by router to identify modules, so it must be unique and with proper registration method it can be used to check module message routing (checking which module is originating an intermodule messages). 
This is related to ADR-33 which is still evolving.

I will rollback the `ModuleID` change and will try to think what do do with the path.
