### ISSUE TITLE
Improve genesis UX for credit class & credit type

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#474]
Currently for ecocredit genesis one needs to explicitly provide a full `CreditType` message in both the params value, as well as identical copies of it in the actual genesis credit classes.

To reduce likelihood of error, I think we should consider either:
1. Providing an additional genesis validation ensuring that all `CreditType` messages listed in a `ClassInfo` are also included in the ecocredit genesis params as one of the allowed `CreditType` values.
2. Allow for `CreditType` value in a `ClassInfo` to only store a reference to a param value (possibly by the abbreviation, or the name?)

**Comment by technicallyty** [comment]
we should probably do 1. regardless

for 2 i think storing only the type abbreviation is the best solution, if not for x/params awkwardness. only issue then becomes if params are changed, and either the credit abbreviation is deleted or changed entirely, then theres no way to fetch the credit type from params anymore. 

I think the benefit of embedding the entirety of CreditType into ClassInfo hinges mostly on the unbrokenness of x/params.. it's really not the ideal structure

**Comment by technicallyty** [comment]
in an effort to move this forward i will layout what i see as the pros/cons between the two possible paths forward. 

## Embedding only the Credit Type Abbreviation in `ClassInfo`
Pros: 
- Less bloat on chain (only storing string and not entire type object)
- More wiggle room to update the type.
- - Can change the name, precision, units -- but **NOT** abbreviation. 

Cons:
To explain the con, it must be understood that x/params is designed to work with SINGLE variable parameters. When you update a param, you're changing the ENTIRE value. This means you cannot append to existing params that are collection types(slices, arrays, maps, etc), you can only overwrite existing collections.

So if one wanted to change the units of a certain type, you'd have to copy all existing types, make the change to whatever type you want to, and then propose the existing collection + change. This leaves some room for human error - not sure to what degree we want to allow for that possibility. 

That being said, the con here is that if we only embed the abbreviation, and the abbreviation gets changed or deleted in a proposal, we now have a broken credit with no type. 

## Embedding the __entire__ credit type in `ClassInfo`
Pros:
- This path gives us maximum assurance of working credits. There is no way for a credit to lose its type with this impl.

Cons: 
- Cannot upgrade types. Once a credit type is assigned to a class, we cannot simply update the param and have it reflected in existing types.
- state bloat -- this method has a larger footprint on the blockchain state, as types are replicated on each class on chain.

**Comment by ruhatch** [comment]
Hmm, even in the second case above, if the governance deletes or modifies abbreviation, the credits aren't really semantically valid anyway, because the governance parameter represents allowed credit types. I think we should go for abbreviation only. Worst case governance scenario is that we lose/modify an abbreviation, but we can then just bring it back with a new proposal (and hopefully it won't happen).

**Comment by ruhatch** [comment]
@technicallyty So to clarify this again, because I'm still not sure, are there no param change validation functions as part of the governance process?

**Comment by technicallyty** [comment]
> @technicallyty So to clarify this again, because I'm still not sure, are there no param change validation functions as part of the governance process?

yeah when someone creates a proposal using this route-> https://github.com/cosmos/cosmos-sdk/blob/master/x/params/proposal_handler.go#L14 it will create a gov handler after the params validateFn is called.

But either way, the param validation wouldn't catch deleting/renaming since its a stateless function

> Worst case governance scenario is that we lose/modify an abbreviation, but we can then just bring it back with a new proposal (and hopefully it won't happen).

+1 this is a good point, embedding abbreviation sounds good then

**Comment by ruhatch** [comment]
@clevinson reminded us to think from point of view of the community or attackers, who might decide to deprecate a credit type or modify the precision value for an existing credit type. In those cases, the precision functionality could break on old credit types and would therefore break all other functionality on the credit.

I can see a couple of solutions:
1. Stateful validation of param changes, meaning we could have validation functions that check updates are append-only
    - This is tricky, because it requires updates to the SDK 
2. Keep the current thing with credit types on ClassInfo, so that even if the credit types change, the type information is still accessible
