### ISSUE TITLE
Hambach Upgrade (v4.0-beta)

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-ledger#682]
Issues that we're waiting on for tagging a `v4.0-beta`, which will be used for the next Hambach Testnet upgrade:

- [x] #578

**Comment by ryanchristo** [comment]
I think we should wait to have an official v4.0 release before relaunching Hambach in order to provide the best user experience, especially if users are wanting to experiment with smart contracts alongside fully functioning modules. In the future, we should track experimental wiring as part of any release epic and milestone. I have added an experimental app wiring section to #818 that includes #578. Closing this epic.
