### ISSUE TITLE
ecocredit refactor follow-ups

### ISSUE THREAD

**Issue by technicallyty** [regen-network/regen-ledger#728]
## Summary

after #696 we will need to:

- [x] refactor marketplace code - @technicallyty 
- - [x] this should probably include refactoring some of the proto endpoints as we've separated the packages. currently we have `proto/regen/ecocredit/market/v1beta1/` and the endpoints are `regen/ecocredit/v1beta1/sell-orders` but these should be changed to `regen/ecocredit/market/v1beta1/sell-orders`
- [ ] refactor server integration tests - #995
- [x] Explicitly set fees in MsgCreateClass #912

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ryanchristo** [comment]
We have separate tracking issues for "refactor simulations" (#920 and #921) so I removed it from here. We should be able to "refactor operations" and "use index delete in expired orders pruning" at this point.

I'm not sure I understand what needs to be done for "refactor tests" - is this related to rewriting acceptance tests using gherkin syntax and then implementing those tests using gocuke? If so, we have separate issues tracking the initial rewriting that needs to be done (#893, #894, #895, #896) and we can open up followup issues for implementing once we have the acceptance tests rewritten. We should also prioritize migrations and features so that we are ready for a v4.0 upgrade if we need added support for bridging polygon assets sooner than later. We could also do some of this work during the audit/testing phase. I think it would be safe to remove "refactor tests" from the list here unless you had something else in mind.

**Comment by technicallyty** [comment]
> I'm not sure I understand what needs to be done for "refactor tests" 

yeah this was a pretty early issue in the re-design/re-factoring, i believe my thoughts at the time were around unit testing. but with that mostly done on a per-PR basis, i think the biggest refactoring of tests would be cleaning up our current integration tests. i imagine things will be broken once the submodules are wired up to the main module
